---
- name: Configure k8s controller
  hosts: all
  remote_user: ubuntu

  tasks:
    - name: Run install script
      ansible.builtin.script:
        cmd: scripts/kubernetes_install.sh
    - name: Initialise cluster
      ansible.builtin.script:
        cmd: scripts/cluster-init.sh
    - name: Generate join token
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
